name: unpuzzle
version: 0.1.0
synopsis: Intstead of playing puzzle games you can make your computer do it for you
description: Please see README.md
maintainer: Dmitry Ivanov <ethercrow@gmail.com>
license: Apache-2.0
github: ethercrow/unpuzzle
category: Tools

ghc-options:
    -Wall
    -ferror-spans

dependencies:
- base >= 4.9 && < 5
- text
- relude
- containers
- lens
- neat-interpolation
- vector

library:
  source-dirs: src

tests:
  tasty:
    main: TestDriver.hs
    source-dirs: test
    ghc-options:
        -Wno-missing-signatures
        -Worphans
    dependencies:
    - unpuzzle
    - hedgehog
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-discover

default-extensions:
- BlockArguments
- DeriveGeneric
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- ViewPatterns
