name: Haskell CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Install C dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -yq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-image-dev
    - name: Build
      run: |
        stack build --fast
    - name: Run tests
      run: stack test

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Install C dependencies
      run: |
        stack exec -- pacman --noconfirm -Syu

        stack exec -- pacman --noconfirm -S \
          mingw64/mingw-w64-x86_64-pkg-config \
          mingw64/mingw-w64-x86_64-SDL2 \
          mingw64/mingw-w64-x86_64-SDL2_ttf \
          mingw64/mingw-w64-x86_64-SDL2_image \
          mingw64/mingw-w64-x86_64-SDL2_mixer

        stack exec -- which pacman
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast
    - name: Run tests
      run: stack test

  build-mac:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Install C dependencies
      run: |
        brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast
    - name: Run tests
      run: stack test
