name: Haskell CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build
    - name: Run tests
      run: stack test
